function [P_i, Wi_list, Ki_list] = switched_riccati_map(...
    P_qtau, alpha_tau, mat_A0, mat_Q0, ...
    mat_A1, mat_Q1, mat_S1, mat_B1, mat_R1, ...
    schedule_seq, state_dim, input_dim ...
)

n_step = size(schedule_seq, 2);

Wi_list{n_step + 1} = P_qtau;
Ki_list{n_step} = [];

for iSeq = 1:n_step

    if schedule_seq(n_step + 1 - iSeq) == 0
        Wi_list{n_step + 1 - iSeq} = mat_Q0 + ...
            alpha_tau * mat_A0' * Wi_list{n_step + 2 - iSeq} * mat_A0;
        Ki_list{n_step + 1 - iSeq} = false;
    elseif schedule_seq(n_step + 1 - iSeq) == 1
        Wi_pre = Wi_list{n_step + 2 - iSeq};
        Wi_list{n_step + 1 - iSeq} = mat_Q1 + ...
            alpha_tau * mat_A1' * Wi_pre * mat_A1 - ...
            (mat_S1 + alpha_tau * mat_A1' * Wi_pre * mat_B1) / ...
            (mat_R1 + alpha_tau * mat_B1' * Wi_pre * mat_B1) * ...
            (alpha_tau * mat_B1' * Wi_pre * mat_A1 + mat_S1');
        
        Ki_list{n_step + 1 - iSeq} = (mat_R1 + ...
            alpha_tau * mat_B1' * Wi_pre * mat_B1) \ ...
            (alpha_tau * mat_B1' * Wi_pre * mat_A1 + mat_S1') * ...
            [eye(state_dim); zeros(input_dim, state_dim)];
    end

end

P_i = Wi_list{1};

end
